# Generated by Django 3.1.4 on 2021-01-05 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youtubeapi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('icon', models.CharField(max_length=10)),
            ],
        ),
        migrations.AlterField(
            model_name='video',
            name='liveBroadcastContent',
            field=models.CharField(choices=[('live', 'Live'), ('upcoming', 'Upcoming'), ('none', 'Archived')], default='none', max_length=10),
        ),
        migrations.AddField(
            model_name='channel',
            name='language',
            field=models.ManyToManyField(to='youtubeapi.Language'),
        ),
    ]
