# Generated by Django 3.1.4 on 2021-01-06 13:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('youtubeapi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('icon', models.ImageField(null=True, upload_to='agencies/')),
            ],
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('icon', models.ImageField(null=True, upload_to='flags_icon/')),
            ],
        ),
        migrations.AlterField(
            model_name='video',
            name='liveBroadcastContent',
            field=models.CharField(choices=[('live', 'Live'), ('upcoming', 'Upcoming'), ('none', 'Archived')], default='none', max_length=10),
        ),
        migrations.AddField(
            model_name='channel',
            name='agency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='youtubeapi.agency'),
        ),
        migrations.AddField(
            model_name='channel',
            name='language',
            field=models.ManyToManyField(blank=True, to='youtubeapi.Language'),
        ),
    ]
