# Generated by Django 3.1.2 on 2021-01-05 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youtubeapi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='liveBroadcastContent',
            field=models.CharField(choices=[('live', 'Live'), ('upcoming', 'Upcoming'), ('none', 'Archived')], default='none', max_length=10),
        ),
    ]
