# Generated by Django 3.1.4 on 2021-01-05 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youtubeapi', '0005_auto_20210105_1110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agency',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='agencies/'),
        ),
    ]
