# Generated by Django 3.1.4 on 2021-01-05 13:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('youtubeapi', '0007_auto_20210105_1839'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channel',
            name='agency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='youtubeapi.agency'),
        ),
        migrations.AlterField(
            model_name='channel',
            name='language',
            field=models.ManyToManyField(blank=True, to='youtubeapi.Language'),
        ),
    ]
